name: Bug report
description: Something is not working as expected ?
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: "##Bug report"
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: This project has a Code of Conduct that all participants are expected to understand and follow.
      options:
        - label: I have read and agree to the Quick Agency Firebase Extensions project's [Code of Conduct](https://github.com/Quick-Agency/firebase-extensions/blob/main/CODE_OF_CONDUCT.md)
          required: true

  - type: dropdown
    id: extension
    attributes:
      label: Extension
      description: What extension is concerned?
      options:
        - firestore-d13n
    validations:
      required: true

  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        1. With this config...
        1. Run '...'
        1. See error...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **Extension version**: 
          - **Firebase Tools version**:
      value: |
        - Extension version:
        - Firebase Tools version:
      render: markdown
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
